<expr> ::= <prop> | <logic> | <future1>
<prop> ::= <bool> | <var> <comp> <num>
<logic> ::= .not <expr> | .or <expr> <expr>
<future1> ::= .globally <expr2> <perc> <perc> | .eventually <expr2> <perc> <perc> | .until <expr2> <expr2> <perc> <perc>
<expr2> ::= <prop> | <logic> | <future2>
<future2> ::= .globally <prop> <perc> <perc> | .globally <logic> <perc> <perc> | .eventually <prop> <perc> <perc> | .eventually <logic> <perc> <perc> | .until <prop> <prop> <perc> <perc> | .until <prop> <logic> <perc> <perc> | .until <logic> <prop> <perc> <perc> | .until <logic> <logic> <perc> <perc>
<num> ::= <digit> <digit> <sign> <digit>
<comp> ::= < | > | <= | >= | ==
<digit> ::= 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 0
<bool> ::= isChangingLane | isApproachingOnramp | isByGuardrail
<var> ::= V_vel | Lane_ID | NE_dist | N_dist | NW_dist | W_dist | SW_dist | S_dist | SE_dist | E_dist
<perc> ::= <digit> <digit>
<sign> ::= + | -
